// Scan a model folder under public/ and emit a ship-data JS module.
//
// Models arrive "dynamically": a model folder holds one sub-folder per
// component type (Brackets/Plates/Stiffeners/Shell — any casing) and each .glb
// inside is one compartment. A type folder (e.g. Shell) may be absent; the
// emitted data simply omits that array, and the viewer copes.
//
// Usage:
//   node scripts/generateModelData.mjs <modelDir> <ExportName> [Vessel Name]
// Example:
//   node scripts/generateModelData.mjs model-2 PetrobrasStruc "PETROBRAS FPSO"

import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// Folder name (lower-cased) -> component-type key used throughout the app.
const FOLDER_TO_TYPE = {
    brackets: 'brackets',
    plates: 'plates',
    stiffeners: 'stiffeners',
    shell: 'shells',
    shells: 'shells',
};

const [, , modelDir, exportName, vesselNameArg] = process.argv;
if (!modelDir || !exportName) {
    console.error('Usage: node scripts/generateModelData.mjs <modelDir> <ExportName> [Vessel Name]');
    process.exit(1);
}

const modelPath = join(ROOT, 'public', modelDir);
const vesselName = vesselNameArg || modelDir.toUpperCase();

const result = {
    vesselId: modelDir,
    vesselName,
};

for (const entry of readdirSync(modelPath)) {
    const entryPath = join(modelPath, entry);
    if (!statSync(entryPath).isDirectory()) continue;

    const type = FOLDER_TO_TYPE[entry.toLowerCase()];
    if (!type) continue;

    const items = readdirSync(entryPath)
        .filter((f) => f.toLowerCase().endsWith('.glb'))
        .sort((a, b) => a.localeCompare(b))
        .map((file) => {
            const compartmentName = file.replace(/\.glb$/i, '');
            return {
                compartmentName,
                uid: compartmentName, // no engineering uid in source files
                link: `/${entry}/${file}`,
            };
        });

    if (items.length > 0) result[type] = items;
}

const outFile = join(ROOT, 'src', 'data', `${modelDir.replace(/-/g, '_')}Data.js`);
const banner = `// AUTO-GENERATED by scripts/generateModelData.mjs from public/${modelDir}.\n` +
    `// Re-run when GLB files are added/removed. Do not edit by hand.\n`;
writeFileSync(
    outFile,
    `${banner}export const ${exportName} = ${JSON.stringify(result, null, 4)};\n`
);

const counts = Object.entries(result)
    .filter(([, v]) => Array.isArray(v))
    .map(([k, v]) => `${k}: ${v.length}`)
    .join(', ');
console.log(`Wrote ${outFile}\n  ${counts}`);
